<?php

namespace CmsBundle\Repository;

/**
 * GalleryPhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalleryPhotoRepository extends \Doctrine\ORM\EntityRepository
{
    public function search($data) {
        // INICJALIZACJA
        $query = $this->createQueryBuilder('p')
            ->join('p.gallery', 'g')
            ->where('g.id = :galleryId')
            ->setParameter('galleryId', $data['galleryId']);

        // WYSZUKIWANIE
        if(isset($data['key'])) {
            $query->andWhere('p.title LIKE :key OR p.alt LIKE :key OR p.description LIKE :key')
                ->setParameter('key', '%'.$data['key'].'%');
        }
        // SORTOWANIE
        if(isset($data['sort'])) {
            $params = explode('.', $data['sort']);

            if (isset($params[1])) {
                $query->orderBy('p.'.$params[0], $params[1]);
            } else {
                $query->orderBy('p.'.$params[0]);
            }

        } else {
            $query->orderBy('p.id', 'ASC');
        }

        return $query->getQuery()->getResult();
    }
}
