<?php

namespace CmsBundle\Repository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends \Doctrine\ORM\EntityRepository
{
    public function search($data)
    {

        // INICJALIZACJA
        $query = $this->createQueryBuilder('p');

        // WYSZUKIWANIE
        if (isset($data['key'])) {
            $query->where('p.title LIKE :key 
                OR p.slug LIKE :key 
                OR p.metaTitle LIKE :key
                OR p.metaDescription LIKE :key
                OR p.metaKeywords LIKE :key')
                ->setParameter('key', '%' . $data['key'] . '%');
        }

        // SORTOWANIE
        if (isset($data['sort'])) {
            $params = explode('.', $data['sort']);

            if (isset($params[1])) {
                $query->orderBy('p.' . $params[0], $params[1]);
            } else {
                $query->orderBy('p.' . $params[0]);
            }

        } else {
            $query->orderBy('p.id', 'ASC');
        }

        return $query->getQuery()->getResult();
    }
}
