<?php

namespace CmsBundle\Repository;

/**
 * SettingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SettingsRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Fetch whole Settings
     *
     * @return array
     */
    public function fetchSettings() {
        $result = array();

        $rows = $this->findAll();

        foreach($rows as $row) {
            $result[$row->getName()] = $row->getValue();
        }

        return $result;
    }

}
